version: '2'
services:
  registry:
    image: llparse/quobyte-server:1.3.11
    environment:
      QUOBYTE_SERVICE: registry
      QUOBYTE_REGISTRY: quobyte-registry-1.rancher.internal:7861,quobyte-registry-2.rancher.internal:7861,quobyte-registry-3.rancher.internal:7861
      QUOBYTE_RPC_PORT: 7861
      QUOBYTE_HTTP_PORT: 7871
      QUOBYTE_LOG_LEVEL: ${QUOBYTE_LOG_LEVEL}
      QUOBYTE_NETWORK: ${QUOBYTE_NETWORK}
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.scheduler.affinity:host_label_soft: quobyte=registry
    ports:
    - 7861:7861/tcp
    - 7861:7861/udp
    - 7871:7871/tcp
    privileged: true
    volumes:
    - ${QUOBYTE_DEVICE_PATH}/:/devices
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
  api:
    image: llparse/quobyte-server:1.3.11
    environment:
      QUOBYTE_SERVICE: api
      QUOBYTE_REGISTRY: quobyte-registry-1.rancher.internal:7861,quobyte-registry-2.rancher.internal:7861,quobyte-registry-3.rancher.internal:7861
      QUOBYTE_API_PORT: 7860
      QUOBYTE_RPC_PORT: 7865
      QUOBYTE_HTTP_PORT: 7875
      QUOBYTE_LOG_LEVEL: ${QUOBYTE_LOG_LEVEL}
      QUOBYTE_NETWORK: ${QUOBYTE_NETWORK}
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.scheduler.affinity:host_label_soft: quobyte=api
    ports:
    - 7860:7860/tcp
    - 7865:7865/tcp
    - 7865:7865/udp
    - 7875:7875/tcp
    privileged: true
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
  webconsole:
    image: llparse/quobyte-server:1.3.11
    environment:
      QUOBYTE_SERVICE: webconsole
      QUOBYTE_REGISTRY: quobyte-registry-1.rancher.internal:7861,quobyte-registry-2.rancher.internal:7861,quobyte-registry-3.rancher.internal:7861
      QUOBYTE_WEBCONSOLE_PORT: 8080
      QUOBYTE_RPC_PORT: 7866
      QUOBYTE_HTTP_PORT: 7876
      QUOBYTE_LOG_LEVEL: ${QUOBYTE_LOG_LEVEL}
      QUOBYTE_NETWORK: ${QUOBYTE_NETWORK}
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.scheduler.affinity:host_label_soft: quobyte=webconsole
    ports:
    - 8080:8080/tcp
    - 7866:7866/tcp
    - 7866:7866/udp
    - 7876:7876/tcp
    privileged: true
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
  metadata:
    image: llparse/quobyte-server:1.3.11
    environment:
      QUOBYTE_SERVICE: metadata
      QUOBYTE_REGISTRY: quobyte-registry-1.rancher.internal:7861,quobyte-registry-2.rancher.internal:7861,quobyte-registry-3.rancher.internal:7861
      QUOBYTE_RPC_PORT: 7862
      QUOBYTE_HTTP_PORT: 7872
      QUOBYTE_LOG_LEVEL: ${QUOBYTE_LOG_LEVEL}
      QUOBYTE_NETWORK: ${QUOBYTE_NETWORK}
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
    ports:
    - 7862:7862/tcp
    - 7862:7862/udp
    - 7872:7872/tcp
    privileged: true
    volumes:
    - ${QUOBYTE_DEVICE_PATH}/:/devices
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
  data:
    image: llparse/quobyte-server:1.3.11
    environment:
      QUOBYTE_SERVICE: data
      QUOBYTE_REGISTRY: quobyte-registry-1.rancher.internal:7861,quobyte-registry-2.rancher.internal:7861,quobyte-registry-3.rancher.internal:7861
      QUOBYTE_RPC_PORT: 7863
      QUOBYTE_HTTP_PORT: 7873
      QUOBYTE_LOG_LEVEL: ${QUOBYTE_LOG_LEVEL}
      QUOBYTE_NETWORK: ${QUOBYTE_NETWORK}
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
    ports:
    - 7863:7863/tcp
    - 7863:7863/udp
    - 7873:7873/tcp
    privileged: true
    volumes:
    - ${QUOBYTE_DEVICE_PATH}/:/devices
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
  client:
    image: llparse/quobyte-client:1.3.11
    environment:
      QUOBYTE_REGISTRY: quobyte-registry-1.rancher.internal:7861,quobyte-registry-2.rancher.internal:7861,quobyte-registry-3.rancher.internal:7861
      QUOBYTE_LOG_LEVEL: ${QUOBYTE_LOG_LEVEL}
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.global: 'true'
    privileged: true
    volumes:
    - ${QUOBYTE_DEVICE_PATH}/quobyte:/quobyte
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'