version: '2'
services:
  client:
    image: llparse/quobyte-client:1.3.11
    command: "/bin/mount.quobyte -f -d INFO ${QUOBYTE_REGISTRY}/ /var/lib/rancher/volumes/quobyte"
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.global: 'true'
    ports:
    - 55000:55000
    privileged: true
    volumes:
    - /var/lib/rancher/volumes/quobyte:/var/lib/rancher/volumes/quobyte:shared
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
  plugin:
    image: llparse/docker-quobyte-plugin:v1.0-beta-2
    command: "-api ${QUOBYTE_API} -path /var/lib/rancher/volumes/quobyte -user ${QUOBYTE_USERNAME} -password ${QUOBYTE_PASSWORD} -registry ${QUOBYTE_REGISTRY}"
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
    links:
    - client
    volumes:
    # this path must line up with the host, because Docker daemon will look for the mount advertised by the container
    - /var/lib/rancher/volumes/quobyte:/var/lib/rancher/volumes/quobyte
    - /run/docker/plugins:/run/docker/plugins
    - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
