version: '2'
services:
  client:
    image: llparse/quobyte-client:1.3.11
    environment:
      QUOBYTE_LOG_LEVEL: DEBUG
      QUOBYTE_REGISTRY: quobyte-registry-1.rancher.internal:7861,quobyte-registry-2.rancher.internal:7861,quobyte-registry-3.rancher.internal:7861
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.global: 'true'
    privileged: true
    volumes:
    - /mnt/quobyte:/quobyte
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'