.catalog:
  version: v1.3.11-rancher0
  minimum_rancher_version: 1.1.4
  questions:
  - variable: VOLUME_NAME
    label: Volume Name
    description: Name of the Quobyte volume to mount
    required: true
    type: string
    default: test