version: '2'
services:
  client:
    image: llparse/quobyte-client:1.3.11
    environment:
      QUOBYTE_REGISTRY: ${QUOBYTE_REGISTRY}
      QUOBYTE_LOG_LEVEL: ${QUOBYTE_LOG_LEVEL}
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.global: 'true'
    ports:
    - 55000:55000
    privileged: true
    volumes:
    - /var/lib/rancher/volumes/quobyte:/quobyte:shared
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
  plugin:
    image: llparse/docker-quobyte-plugin:v1.0-beta-2
    command: "-api ${QUOBYTE_API} -path /quobyte -registry ${QUOBYTE_REGISTRY} -user ${QUOBYTE_USER} -password ${QUOBYTE_PASSWORD}"
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
    volumes:
    - /var/lib/rancher/volumes/quobyte:/quobyte:shared
    - /run/docker/plugins:/run/docker/plugins
    - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
